name: Pruebas Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: "./desarrollo web - curso"

      - name: Start static server
        run: npx http-server -p 5500 &
        working-directory: "./desarrollo web - curso"
        env:
          CI: true

      - name: Wait for server
        run: npx wait-on http://localhost:5500
   

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: "./desarrollo web - curso"
