name: Pruebas Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install http-server globally
        run: npm install -g http-server

      - name: Start static server for todoList
        run: http-server ./todoList -p 5500 &
        
      - name: Wait for the application to be ready
        run: npx wait-on http://localhost:5500

      - name: Run Cypress tests
        run: npx cypress run
